### ISSUE TITLE
Can't open maximized (miscalculating drawer)

### ISSUE THREAD

**Issue by yurigoytacaz** [markhuot/projectplus#8]
Everytime I open a new project/folder, I need to **maximize** the window. 
Textmate is thinking that my window _has_ a **drawer** and leave that space empty and doesn't fill that space with the Textmate's window. (shot: http://d.pr/m32t)
I thought that it was just don't remembering the window position but I came to conclusion that is the "drawer" that I use as sidebar that is the "issue".

Keep up the good work!

**Comment by caiogondim** [comment]
Same for me =/

**Comment by markhuot** [comment]
Sorry guys, this is a bug in the underlying ProjectPlus plugin I believe. I don't do anything in my fork with the window layout or positioning.

That said, the original fork is showing it's age (several Lion quirks) that may warrant a rewrite… someday…
